# Generated by Django 5.2.4 on 2025-07-03 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('website', models.URLField(blank=True, unique=True)),
                ('country', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=5)),
                ('industry_category', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('activity_level', models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], max_length=10)),
                ('acquired_via', models.CharField(max_length=100)),
                ('lead_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(max_length=254)),
                ('phone_office', models.CharField(max_length=20)),
                ('phone_mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('customer_specific_condition', models.CharField(max_length=200)),
                ('business_card', models.FileField(blank=True, upload_to='business_cards/', verbose_name='Business Card')),
                ('document', models.FileField(blank=True, upload_to='contact_documents/', verbose_name='Document')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='gwm_crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green')),
                ('summary', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='gwm_crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='gwm_crm.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('qualified', 'Qualified'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], max_length=20)),
                ('expected_value', models.IntegerField()),
                ('expected_close_date', models.DateTimeField(blank=True, null=True)),
                ('probability', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='gwm_crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('price_list', models.FileField(blank=True, upload_to='price_lists/', verbose_name='Price List')),
                ('price_list_expiry', models.DateTimeField(blank=True, null=True)),
                ('volume_offered', models.CharField(max_length=200)),
                ('delivery_terms', models.CharField(max_length=200)),
                ('packaging', models.CharField(max_length=200)),
                ('payment_terms', models.CharField(max_length=200)),
                ('product_specifications', models.TextField()),
                ('target_price', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gwm_crm.company')),
            ],
        ),
    ]
