# Generated by Django 5.2.4 on 2025-07-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwm_crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='customer_specific_condition',
            new_name='customer_specific_conditions',
        ),
    ]
