# Generated by Django 5.2.4 on 2025-07-15 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwm_crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Assigned User'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='attachment',
            field=models.FileField(blank=True, upload_to='meetings_attachments/', verbose_name='Meeting Attachments'),
        ),
        migrations.CreateModel(
            name='InteractionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='interaction_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gwm_crm.interaction')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('task_due_soon', 'Task Due Soon'), ('meeting_due_soon', 'Meeting Due Soon'), ('task_assigned', 'Task Assigned')], max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
