# Generated by Django 5.2.4 on 2025-07-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwm_crm', '0002_rename_customer_specific_condition_contact_customer_specific_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='document',
        ),
        migrations.CreateModel(
            name='ContactDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contact_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gwm_crm.contact')),
            ],
        ),
    ]
