# Generated by Django 5.2.4 on 2025-07-15 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwm_crm', '0002_interaction_assigned_to_meeting_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiondocument',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gwm_crm.interaction'),
        ),
    ]
