# Generated by Django 5.2.4 on 2025-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwm_crm', '0003_alter_interactiondocument_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='business_card',
        ),
        migrations.AddField(
            model_name='company',
            name='business_card',
            field=models.FileField(blank=True, upload_to='business_cards/', verbose_name='Business Card'),
        ),
        migrations.AddField(
            model_name='company',
            name='catalogs',
            field=models.FileField(blank=True, upload_to='catalogs/', verbose_name='Catalogs'),
        ),
        migrations.AddField(
            model_name='company',
            name='correspondence',
            field=models.FileField(blank=True, upload_to='correspondence/', verbose_name='Correspondence'),
        ),
        migrations.AddField(
            model_name='company',
            name='signed_contracts',
            field=models.FileField(blank=True, upload_to='signed_contracts/', verbose_name='Signed_Contracts'),
        ),
    ]
