# Generated by Django 5.2.4 on 2025-07-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwm_crm', '0004_remove_contact_business_card_company_business_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_card',
            field=models.FileField(blank=True, null=True, upload_to='business_cards/', verbose_name='Business Card'),
        ),
        migrations.AlterField(
            model_name='company',
            name='catalogs',
            field=models.FileField(blank=True, null=True, upload_to='catalogs/', verbose_name='Catalogs'),
        ),
        migrations.AlterField(
            model_name='company',
            name='correspondence',
            field=models.FileField(blank=True, null=True, upload_to='correspondence/', verbose_name='Correspondence'),
        ),
        migrations.AlterField(
            model_name='company',
            name='signed_contracts',
            field=models.FileField(blank=True, null=True, upload_to='signed_contracts/', verbose_name='Signed_Contracts'),
        ),
    ]
