# Generated by Django 5.2.4 on 2025-07-19 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwm_crm', '0006_product_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='users',
            field=models.ManyToManyField(related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Attendees'),
        ),
    ]
